version: '3.8'

services:
  #===================== INFRA =========================#
  builder:
    privileged: true
    image: node:18.16.0-buster-slim
    volumes:
      - ./../yarn.lock:/app/yarn.lock
      - ./../package.json:/app/package.json
      - ./../apps:/app/apps
      - ./../libs:/app/libs
      - ./../nx.json:/app/nx.json
      - ./../tsconfig.base.json:/app/tsconfig.base.json
      - ./data/node_modules:/app/node_modules
      - ./data/dist:/app/dist
    working_dir: /app
    command:
      - sh
      - -c
      - |
        whoami
        apt update -y && apt install python3 git make build-essential -y
        yarn install
        yarn build:all
        exit 0

  pg_db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data/

  broker-issuer:
    profiles:
      - issuer
    command: ["-js", "-sd", "/data", "-m","8222", "-D"]
    container_name: broker-issuer
    image: 'nats:latest'
    ports:
      - '4222' #Nats server port
      - '8222:8222' #Nats server Monitering port
    volumes:
      - ./data/issuer/nats/:/data/

  broker-holder:
    profiles:
      - holder
    command: ["-js", "-sd", "/data", "-m","8222", "-D"]
    container_name: broker-holder
    image: 'nats:latest'
    ports:
      - '4222' #Nats server port
      - '8223:8222' #Nats server Monitering port
    volumes:
      - ./data/holder/nats/:/data/

