version: '3.8'

services:
  pg_db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data/

  broker:
    command: ["-js", "-sd", "/data", "-m","8222", "-D"]
    container_name: broker
    image: 'nats:latest'
    ports:
      - '4222:4222' #Nats server port
      - '8222:8222' #Nats server Monitering port
    volumes:
      - ./data/nats/:/data/

